[project]
name = "brush-tool"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "pillow>=12.2.0",
    "pyinstaller>=6.20.0",
    "pynput>=1.8.2",
    "python-multipart>=0.0.30",
    "pywebview>=6.2.1",
    "uvicorn>=0.48.0",
]
